[package]
name = "sana"
version = "0.1.0"
authors = ["Colin <email@colinlogue.me>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
vec2dim = "0.3.2"
rand = "0.7"